# Based on https://github.com/koalaman/shellcheck/wiki/TravisCI

sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/source/init.sh
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/source/text_editor.sh
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/source/keyboard-shortcuts.sh
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/source/directory-navigation.sh
 - docker run -v $(pwd):/scripts koalaman/shellcheck /scripts/source/prompt.sh
