# Based on https://github.com/koalaman/shellcheck/wiki/TravisCI

sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/scripts koalaman/shellcheck -x source/init.sh source/keyboard-shortcuts.sh source/directory-navigation.sh source/text_editor.sh
